import "./globals.css";
import Footer from "@/components/ui/footer";
import Navbar from "@/components/ui/navbar";
import ClientOnlyTargetCursor from "@/components/ui/ClientOnlyTargetCursor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className="overflow-x-hidden font-sans"
        suppressHydrationWarning={true}
      >
        <div>
          <ClientOnlyTargetCursor spinDuration={2} hideDefaultCursor={true} />
          <Navbar />
          <main className="flex-grow w-full h-full">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
