"use client";

/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/gU-KjpRSvoZxGltT/scene.splinecode"
  );

  return (
    <>
      <color attach="background" args={["#000000"]} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <OrthographicCamera
            name="Camera"
            makeDefault={true}
            zoom={1.36}
            far={100000}
            near={-100000}
            position={[-859.67, 280.82, 516.91]}
            rotation={[-0.46, -0.81, -0.34]}
          />
          <spotLight
            name="Spot Light"
            castShadow
            intensity={1}
            angle={Math.PI / 6}
            penumbra={1}
            distance={2000}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            color="#c188f1"
            position={[-500.58, 331.88, -201.63]}
            rotation={[0, 0, 0.64]}
            scale={1}
          />
          <spotLight
            name="Spot Light1"
            castShadow
            intensity={1}
            angle={Math.PI / 6}
            penumbra={1}
            distance={2000}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-fov={119.99999999999999}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            color="#f9baba"
            position={[464.42, 346.97, -201.63]}
            rotation={[0, 0, -0.63]}
          />
          <mesh
            name="Plane"
            geometry={nodes?.Plane?.geometry}
            material={materials?.["Silver Roughness 01"]}
            castShadow
            receiveShadow
            position={[-16.87, -241.73, -191.6]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube"
            geometry={nodes?.Cube?.geometry}
            material={materials?.["Silver Roughness 01"]}
            castShadow
            receiveShadow
            position={[0.5, -183.08, -203.87]}
          />
          <group name="Cuerpo" position={[0, -83.5, -206.97]}>
            <mesh
              name="Cube 2"
              geometry={nodes?.["Cube 2"]?.geometry}
              material={materials?.["Silver Roughness 01"]}
              castShadow
              receiveShadow
              position={[0, -11.72, 0]}
              rotation={[1.57, 0, 0]}
              scale={[1.22, 1, 0.31]}
            />
            <mesh
              name="Cube 4"
              geometry={nodes?.["Cube 4"]?.geometry}
              material={materials?.["Silver Roughness 01"]}
              castShadow
              receiveShadow
              position={[10.45, -28.91, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.34, 0.41, 0.4]}
            />
            <mesh
              name="Cube 3"
              geometry={nodes?.["Cube 3"]?.geometry}
              material={materials?.["Silver Roughness 01"]}
              castShadow
              receiveShadow
              position={[-13, -28.91, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.34, 0.41, 0.4]}
            />
            <mesh
              name="Cube1"
              geometry={nodes?.Cube1?.geometry}
              material={materials?.["Silver Roughness 01"]}
              castShadow
              receiveShadow
              position={[0, 18.02, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.22, 1, 0.79]}
            />
          </group>
          <group
            name="Cabeza"
            position={[-0.12, 0, -203.45]}
            rotation={[-0.6, 0, 0]}
          >
            <group name="Ears" position={[0, 6, -5.92]}>
              <mesh
                name="Cylinder 2"
                geometry={nodes?.["Cylinder 2"]?.geometry}
                material={materials?.["Silver Roughness 01"]}
                castShadow
                receiveShadow
                position={[-60.27, 0, 0]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.42}
              />
              <mesh
                name="Cylinder"
                geometry={nodes?.Cylinder?.geometry}
                material={materials?.["Silver Roughness 01"]}
                castShadow
                receiveShadow
                position={[60.27, 0, 0]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={1.42}
              />
            </group>
            <group name="Ojos" position={[0.31, -0.19, 0.54]} scale={1}>
              <mesh
                name="Sphere 3"
                geometry={nodes?.["Sphere 3"]?.geometry}
                material={materials?.["Studio Lighting 04_1"]}
                castShadow
                receiveShadow
                position={[-22.32, 10.24, 33.73]}
              />
              <mesh
                name="Sphere 2"
                geometry={nodes?.["Sphere 2"]?.geometry}
                material={materials?.["Studio Lighting 04_1"]}
                castShadow
                receiveShadow
                position={[22.68, 10.24, 34.79]}
              />
              <mesh
                name="Boolean 2"
                geometry={nodes?.["Boolean 2"]?.geometry}
                material={nodes?.["Boolean 2"]?.material}
                castShadow
                receiveShadow
                position={[22.68, 10.24, 41.14]}
              />
            </group>
            <mesh
              name="Boolean"
              geometry={nodes?.Boolean?.geometry}
              material={nodes?.Boolean?.material}
              castShadow
              receiveShadow
              position={[0.12, 0, -3.57]}
            />
          </group>
          <OrthographicCamera
            name="1"
            makeDefault={false}
            far={10000}
            near={-50000}
          />
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#eaeaea"
          />
        </scene>
      </group>
    </>
  );
}
